[package]
name = "gemini-rs"
version = "0.2.0"
edition = "2021"
license = "MIT"
description = "A library to interact with the Google Gemini API"

[dependencies]
reqwest = "0.12.9"
tokio = { version = "1.41.0", features = ["full"] }
