[package]
name = "gemini-rs"
version = "0.2.2"
edition = "2021"
license = "MIT"
description = "A library to interact with the Google Gemini API"

[dependencies]
json = "0.12.4"
reqwest = "0.12.9"
thiserror = "1.0.66"
tokio = { version = "1.41.0", features = ["full"] }
